---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

inputs:
  - name: java-src
    path: src
  - name: glibc-build

outputs:
  - name: java-build
  
run:
  path: ./src/build.sh
