---
platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/fedora, tag: build}

run:
  path: src/build.sh
    
inputs:
  - name: java-src
    path: src
  - name: glibc

outputs:
  - name: out

